### ISSUE TITLE
v1.4 Visual not working in IE 11

### ISSUE THREAD

**Issue by batchelderb** [fredrikheden/summarytable#10]
Thank you for including row calculations with any expression. I have been eagerly awaiting this functionality. I downloaded your new pbiviz and went to use it in my pbix file and it shows up blank IE11. Then, I used your sample file and imported the 1.4 visual into it. This shows up blank in IE11 but works in chrome and power bi desktop. I have attached two screenshots to showcase the error. 

Power BI Desktop - 
![v1 4 power bi desktop](https://user-images.githubusercontent.com/49289202/55583209-4d908480-56ef-11e9-8a43-61dfc2a6b8c1.png)

The left visual (I assume it is 1.3) and right visual  (which is 1.4) both work in Desktop and Chrome.

IE 11-
![v1 4 - IE11](https://user-images.githubusercontent.com/49289202/55583208-4d908480-56ef-11e9-889c-cdb213c01a63.png)

You can see the left visual works, but the right visual is blank.

**Comment by fredrikheden** [comment]
Thank's for highlighting this!
There is now an updated version (v1.4.1) with this issue resolved.

**Comment by batchelderb** [comment]
Thanks for the quick fix! Much appreciated!
