### ISSUE TITLE
Row Formatting

### ISSUE THREAD

**Issue by lsutrey** [fredrikheden/summarytable#11]
Hi,

Love this visual!  I'm not an expert with CSS, though I am learning just by playing around with this visual.  However, I have not been able to figure out how you achieved the various row shadings in your examples.  Can you advise on the parameters needed for shading specific rows in a column?  I'm trying to create an alternating background color.  

Many thanks!

Trey

**Comment by fredrikheden** [comment]
Hi,
To style a row you need to apply styling to that specific row’s rowStyle property. Look at the sample in the samples folder.

**Comment by lsutrey** [comment]
I totally missed the .pbix sample.  My bad.  That is just what I needed.  Thank you very much!
