### ISSUE TITLE
Not all rows generated automatically

### ISSUE THREAD

**Issue by LottaGit** [fredrikheden/summarytable#6]
Hi, 

In an example with  17 row, only 7 row are generated in the Generate template from field list.
See attached screendump.
Which is fine - I just wondered if that was the desired result.
I just want to know how to instruct end-users.

Thanks
![Skärmklipp_SummaryTable](https://user-images.githubusercontent.com/36202145/54273493-4958c780-4586-11e9-9b70-82c8821f75a3.JPG)

**Comment by fredrikheden** [comment]
This is the desired result. The result that is generated (the template) is only created to get started with the syntax. The specific rows that should be displayed needs to be added to the json.

**Comment by LottaGit** [comment]
Thanks - thought that was it. :)
